### PR TITLE
Restore proxied mutated elements (solves #4)

### PR DESCRIPTION
**Pull request by blahah**
Store the ID (if any) of an element on its proxy, then use ID comparison for isSameNode

### CODE REVIEW

**Comment by bcomnes** [comment]
LGTM.  I'm Mobile at the moment, so @blahah feel free to merge and publish if you want this sooner.

**Comment by bcomnes** [comment]
Sweet.  I'll release later today.  I want to set up some https://github.com/juliangruber/browser-run tests so that we can test with real dom nodes.

**Comment by bcomnes** [comment]
Published as cache-component@3.0.0-3

**Comment by blahah** [comment]
@bcomnes yeah it would be really nice to have some performance metrics as well so we can see regressions

**Pull request merged**
