### PR TITLE
Merge cache-component and nanocomponent (6.0.0)

### PR DESCRIPTION
**Pull request by bcomnes**
This adds optional `_load` and `_unload` lifecycle methods to cache-component.  It also removes `_willUpdate` since its redundant with `_update` (anything you can do in update you can do in didUpdate).

It also renames `_{will,did}Mount` to `_{will,did}Render`.  We might remove those though, although didRender is still a handy observer free way to interact with a dom node that is freshly mounted in the page, and the on-load hooks are mounted at the same scope as willMount, so maybe those can be merged somehow.  

Things left to do:

- [x] re-add onload
- [x] finalize lifecycle hooks
- [x] Update Docs
- [x] Rename to nanocomponent
- [ ] Add upgrade guide for cache-component and nano component 5
- [x] Fix tests
- [ ] Add browser tests (https://gist.github.com/bcomnes/fa4fa3a83807b4189356699c17207a0b)
- [x] Update examples
- [ ] Make examples runnable (component playground? perhaps put this off)
- [ ] merge with nanocomponent and move to choo org

### CODE REVIEW

**Comment by bcomnes** [comment]
Also renames `this._element` to `this.element`.

**Comment by toddself** [comment]
I definitely like `render` more than `mount` in this context since we're not dealing with a virtual dom.  THis looks good!

**Comment by blahah** [comment]
`render` to me implies generating the graphics (like `paint` in the browser devtools), where `mount` implies attaching it to the DOM. Does that interpretation match other people's?

**Comment by blahah** [comment]
actually `render` comes before `paint` - generating  the graphics in memory vs drawing on the screen

**Comment by bcomnes** [comment]
I changed it to render from mount because all cache-component does by those points is hand the fully rendered element off to the caller.  It might not be mounted yet.  You have to use _load to know for sure its in the dom.

In practice though with choo, its in the dom by the time didRender is called.

@yoshuawuyts and I are debating if we should keep these lifecycle hooks.

**Comment by bcomnes** [comment]
@yoshuawuyts do you want to move nanocomponent to the choo org, and I can merge this branch with that repo?  Its not quite ready for release yet but we can at least get this going in the correct repo

**Comment by yoshuawuyts** [comment]
Nanocomponent is part of the choo org ✨
https://github.com/choojs/nanocomponent

**Comment by bcomnes** [comment]
```
bret: for example: we could remove the ES6 example, and put it together with the constructor bind under the same heading
09:35 bret: most of what's different is the way it's constructed, and from there it makes sense - copying the whole initial example makes it trickier to maintain I think
```

**Comment by yoshuawuyts** [comment]
PR here https://github.com/hypermodules/cache-component/pull/19

**Comment by toddself** [comment]
What about putting the examples up on glitch?  It would make them very easily runable and people could even easily clone them to mess around?

**Comment by bcomnes** [comment]
I'm not familiar with how glitch works, but I'm open to it 👍

**Comment by toddself** [comment]
@bcomnes here's a little choo in glitch! https://glitch.com/edit/#!/choo-todo

it's like codepen, but way cooler

**Comment by bcomnes** [comment]
I was going to do a component showcase but that sounds easier tbh

**Comment by bcomnes** [comment]
Closing and moving over to https://github.com/choojs/nanocomponent/pull/38

**Pull request closed without merging**
